### ISSUE TITLE
Los Sprites están muy pixelados y no reconoce los sprites

### ISSUE THREAD

**Issue by Keytaro2** [acxz/pokeshell#21] opened 2024-09-08 20:38 UTC
https://github.com/user-attachments/assets/0f41ae2e-7037-4cc6-a3b3-d3fa8c834288

Uploading new.mp4…

En termux android

**Comment by Keytaro2** [comment] 2024-09-08 21:03
Uploading new.mp4…

**Comment by Keytaro2** [comment] 2024-09-08 21:17
Uploading new.mp4…

**Comment by acxz** [comment] 2024-10-27 00:30
duplicate of #13 

just want to point out that it is pretty cool you have it working on android!

**Closed by acxz** 2024-10-27 00:30 UTC
