### ISSUE TITLE
How can I get the sprites to be more defined 

### ISSUE THREAD

**Issue by Juanjo8918** [acxz/pokeshell#22] opened 2024-10-02 01:11 UTC
The sprites done look like the example posted. Is there anything im missing? 
![Screenshot_20241001_211028](https://github.com/user-attachments/assets/505f3f84-6769-4a5d-8033-62a2649605f3)

**Comment by Juanjo8918** [comment] 2024-10-02 01:27
It also looks the same on the kitty terminal

**Comment by acxz** [comment] 2024-10-27 00:29
duplicate of #13

**Closed by acxz** 2024-10-27 00:29 UTC
