### ISSUE TITLE
not working with neowofetch

### ISSUE THREAD

**Issue by idgafox** [acxz/pokeshell#12] opened 2022-12-08 12:37 UTC
I have arch with i3-gaps, using kitty terminal and running with neowofetch.
I've set image_source="$(pokeshell eevee)" but the issue is that when I run it, instead of showing up on the side, it shows on top of it, and I don't know how to change it.

![image](https://user-images.githubusercontent.com/119700331/206447921-96986be4-d3b2-4e55-a366-e6698668e43b.png)

**Comment by acxz** [comment] 2023-02-23 15:21
hmm that is really weird as I can't seem to reproduce it.
Can you paste your neowofetch config?

**Comment by acxz** [comment] 2024-09-21 22:58
Closing due to lack of information required for debugging.

**Closed by acxz** 2024-09-21 22:58 UTC
