### ISSUE TITLE
Sprites  animations appear very pixellated and broken

### ISSUE THREAD

**Issue by tenstriip** [acxz/pokeshell#20] opened 2024-09-02 10:32 UTC
Sprites look rendered incorrectly and flicker. 
Errors state: The convert command is deprecated in IMv7, use "magick" instead or convert" or "magick convert"

**Comment by acxz** [comment] 2024-10-27 00:02
thanks for opening this @tenstriip , I'm now using `magick` as for the animations that is a duplicate of #13

**Closed by acxz** 2024-10-27 00:02 UTC
